class Countries{
  String countyFlagImg;
  String countryFlagName;
  String countryCode;
  String isoCode;

  Countries({
    required this.countyFlagImg,
    required this.countryFlagName,
    required this.countryCode,
    required this.isoCode,
  });
}

List<Countries> countryList = [
  //Starting with A
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AF.png',
    countryFlagName: 'Afghanistan',
    countryCode: '93',
    isoCode: 'AFG',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AL.png',
    countryFlagName: 'Albania',
    countryCode: '355',
    isoCode: 'ALB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/DZ.png',
    countryFlagName: 'Algeria',
    countryCode: '213',
    isoCode: 'DZA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AD.png',
    countryFlagName: 'Andorra',
    countryCode: '376',
    isoCode: 'AND',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AO.png',
    countryFlagName: 'Angola',
    countryCode: '244',
    isoCode: 'AGO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AR.png',
    countryFlagName: 'Argentina',
    countryCode: '54',
    isoCode: 'ARG',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AM.png',
    countryFlagName: 'Armenia',
    countryCode: '374',
    isoCode: 'ARM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AU.png',
    countryFlagName: 'Australia',
    countryCode: '61',
    isoCode: 'AUS',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AT.png',
    countryFlagName: 'Austria',
    countryCode: '43',
    isoCode: 'AUT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/a_flags/AZ.png',
    countryFlagName: 'Azerbaijan',
    countryCode: '994',
    isoCode: 'AZE',
  ),
  // flag starting with B
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BS.png',
    countryFlagName: 'Bahamas',
    countryCode: '1-242',
    isoCode: 'BHS',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BH.png',
    countryFlagName: 'Bahrain',
    countryCode: '973',
    isoCode: 'BHR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BD.png',
    countryFlagName: 'Bangladesh',
    countryCode: '880',
    isoCode: 'BGD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BB.png',
    countryFlagName: 'Barbados',
    countryCode: '1-246',
    isoCode: 'BRB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BY.png',
    countryFlagName: 'Belarus',
    countryCode: '375',
    isoCode: 'BLR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BE.png',
    countryFlagName: 'Belgium',
    countryCode: '32',
    isoCode: 'BEL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BZ.png',
    countryFlagName: 'Belize',
    countryCode: '501',
    isoCode: 'BLZ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BJ.png',
    countryFlagName: 'Benin',
    countryCode: '229',
    isoCode: 'BEN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BT.png',
    countryFlagName: 'Bhutan',
    countryCode: '975',
    isoCode: 'BTN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BO.png',
    countryFlagName: 'Bolivia',
    countryCode: '591',
    isoCode: 'BOL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BW.png',
    countryFlagName: 'Botswana',
    countryCode: '267',
    isoCode: 'BWA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BR.png',
    countryFlagName: 'Brazil',
    countryCode: '55',
    isoCode: 'BRA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BN.png',
    countryFlagName: 'Brunei',
    countryCode: '673',
    isoCode: 'BRN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BG.png',
    countryFlagName: 'Bulgaria',
    countryCode: '359',
    isoCode: 'BGR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BF.png',
    countryFlagName: 'Burkina Faso',
    countryCode: '226',
    isoCode: 'BFA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/b_flags/BI.png',
    countryFlagName: 'Burundi',
    countryCode: '257',
    isoCode: 'BDI',
  ),
  // Flag Starting with C
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/KH.png',
    countryFlagName: 'Cambodia',
    countryCode: '855',
    isoCode: 'KHM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CM.png',
    countryFlagName: 'Cameroon',
    countryCode: '237',
    isoCode: 'CMR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CA.png',
    countryFlagName: 'Canada',
    countryCode: '1',
    isoCode: 'CAN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CV.png',
    countryFlagName: 'Cape Verde',
    countryCode: '238',
    isoCode: 'CPV',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/TD.png',
    countryFlagName: 'Chad',
    countryCode: '235',
    isoCode: 'TCD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CL.png',
    countryFlagName: 'Chile',
    countryCode: '56',
    isoCode: 'CHL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CN.png',
    countryFlagName: 'China',
    countryCode: '86',
    isoCode: 'CHN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CO.png',
    countryFlagName: 'Colombia',
    countryCode: '57',
    isoCode: 'COL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/KM.png',
    countryFlagName: 'Comoros',
    countryCode: '269',
    isoCode: 'COM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CR.png',
    countryFlagName: 'Costa Rica',
    countryCode: '506',
    isoCode: 'CRI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/HR.png',
    countryFlagName: 'Croatia',
    countryCode: '385',
    isoCode: 'HRV',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CU.png',
    countryFlagName: 'Cuba',
    countryCode: '53',
    isoCode: 'CUB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CY.png',
    countryFlagName: 'Cyprus',
    countryCode: '357',
    isoCode: 'CYP',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/c_flags/CZ.png',
    countryFlagName: 'Czech Republic',
    countryCode: '420',
    isoCode: 'CZE',
  ),
  //Flag with D
  Countries(
    countyFlagImg: 'assets/country_flags/d_flags/DK.png',
    countryFlagName: 'Denmark',
    countryCode: '45',
    isoCode: 'DNK',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/d_flags/DJ.png',
    countryFlagName: 'Djibouti',
    countryCode: '253',
    isoCode: 'DJI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/d_flags/DM.png',
    countryFlagName: 'Dominica',
    countryCode: '1-767',
    isoCode: 'DMA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/d_flags/DO.png',
    countryFlagName: 'Dominican Republic',
    countryCode: '1-809',
    isoCode: 'DOM',
  ),
  //Flag with E
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/EC.png',
    countryFlagName: 'Ecuador',
    countryCode: '593',
    isoCode: 'ECU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/EG.png',
    countryFlagName: 'Egypt',
    countryCode: '20',
    isoCode: 'EGY',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/SV.png',
    countryFlagName: 'El Salvador',
    countryCode: '503',
    isoCode: 'SLV',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/GQ.png',
    countryFlagName: 'Equatorial Guinea',
    countryCode: '240',
    isoCode: 'GNQ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/ER.png',
    countryFlagName: 'Eritrea',
    countryCode: '291',
    isoCode: 'ERI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/EE.png',
    countryFlagName: 'Estonia',
    countryCode: '372',
    isoCode: 'EST',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/e_flags/ET.png',
    countryFlagName: 'Ethiopia',
    countryCode: '251',
    isoCode: 'ETH',
  ),
  //Flag with f
  Countries(
    countyFlagImg: 'assets/country_flags/f_flags/FJ.png',
    countryFlagName: 'Fiji',
    countryCode: '679',
    isoCode: 'FJI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/f_flags/FI.png',
    countryFlagName: 'Finland',
    countryCode: '358',
    isoCode: 'FIN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/f_flags/FR.png',
    countryFlagName: 'France',
    countryCode: '33',
    isoCode: 'FRA',
  ),
  //Flags with G
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GA.png',
    countryFlagName: 'Gabon',
    countryCode: '241',
    isoCode: 'GAB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GM.png',
    countryFlagName: 'Gambia',
    countryCode: '220',
    isoCode: 'GMB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GE.png',
    countryFlagName: 'Georgia',
    countryCode: '995',
    isoCode: 'GEO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/DE.png',
    countryFlagName: 'Germany',
    countryCode: '49',
    isoCode: 'DEU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GH.png',
    countryFlagName: 'Ghana',
    countryCode: '233',
    isoCode: 'GHA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GR.png',
    countryFlagName: 'Greece',
    countryCode: '30',
    isoCode: 'GRC',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GD.png',
    countryFlagName: 'Grenada',
    countryCode: '1-473',
    isoCode: 'GRD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GT.png',
    countryFlagName: 'Guatemala',
    countryCode: '502',
    isoCode: 'GTM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GN.png',
    countryFlagName: 'Guinea',
    countryCode: '224',
    isoCode: 'GIN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GW.png',
    countryFlagName: 'Guinea-Bissau',
    countryCode: '245',
    isoCode: 'GNB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/g_flags/GY.png',
    countryFlagName: 'Guyana',
    countryCode: '592',
    isoCode: 'GUY',
  ),
  //flags with H
  Countries(
    countyFlagImg: 'assets/country_flags/h_flags/HT.png',
    countryFlagName: 'Haiti',
    countryCode: '509',
    isoCode: 'HTI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/h_flags/HN.png',
    countryFlagName: 'Honduras',
    countryCode: '504',
    isoCode: 'HND',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/h_flags/HU.png',
    countryFlagName: 'Hungary',
    countryCode: '36',
    isoCode: 'HUN',
  ),
  //flags with I
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IS.png',
    countryFlagName: 'Iceland',
    countryCode: '354',
    isoCode: 'ISL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IN.png',
    countryFlagName: 'India',
    countryCode: '91',
    isoCode: 'IND',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/ID.png',
    countryFlagName: 'Indonesia',
    countryCode: '62',
    isoCode: 'IDN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IR.png',
    countryFlagName: 'Iran',
    countryCode: '98',
    isoCode: 'IRN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IQ.png',
    countryFlagName: 'Iraq',
    countryCode: '964',
    isoCode: 'IRQ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IE.png',
    countryFlagName: 'Ireland',
    countryCode: '353',
    isoCode: 'IRL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IL.png',
    countryFlagName: 'Israel',
    countryCode: '972',
    isoCode: 'ISR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/IT.png',
    countryFlagName: 'Italy',
    countryCode: '39',
    isoCode: 'ITA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/i_flags/CI.png',
    countryFlagName: 'Ivory Coast',
    countryCode: '225',
    isoCode: 'CIV',
  ),
  //flags with J
  Countries(
    countyFlagImg: 'assets/country_flags/j_flags/JM.png',
    countryFlagName: 'Jamaica',
    countryCode: '1-876',
    isoCode: 'JAM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/j_flags/JP.png',
    countryFlagName: 'Japan',
    countryCode: '81',
    isoCode: 'JPN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/j_flags/JO.png',
    countryFlagName: 'Jordan',
    countryCode: '962',
    isoCode: 'JOR',
  ),
  //flags with K
  Countries(
    countyFlagImg: 'assets/country_flags/k_flags/KZ.png',
    countryFlagName: 'Kazakhstan',
    countryCode: '7',
    isoCode: 'KAZ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/k_flags/KE.png',
    countryFlagName: 'Kenya',
    countryCode: '254',
    isoCode: 'KEN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/k_flags/KI.png',
    countryFlagName: 'Kiribati',
    countryCode: '686',
    isoCode: 'KIR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/k_flags/KW.png',
    countryFlagName: 'Kuwait',
    countryCode: '965',
    isoCode: 'KWT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/k_flags/KG.png',
    countryFlagName: 'Kyrgyzstan',
    countryCode: '996',
    isoCode: 'KGZ',
  ),
  //flags with L
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LA.png',
    countryFlagName: 'Laos',
    countryCode: '856',
    isoCode: 'LAO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LV.png',
    countryFlagName: 'Latvia',
    countryCode: '371',
    isoCode: 'LVA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LB.png',
    countryFlagName: 'Lebanon',
    countryCode: '961',
    isoCode: 'LBN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LS.png',
    countryFlagName: 'Lesotho',
    countryCode: '266',
    isoCode: 'LSO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LR.png',
    countryFlagName: 'Liberia',
    countryCode: '231',
    isoCode: 'LBR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LY.png',
    countryFlagName: 'Libya',
    countryCode: '218',
    isoCode: 'LBY',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LI.png',
    countryFlagName: 'Liechtenstein',
    countryCode: '423',
    isoCode: 'LIE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LT.png',
    countryFlagName: 'Lithuania',
    countryCode: '370',
    isoCode: 'LTU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/l_flags/LU.png',
    countryFlagName: 'Luxembourg',
    countryCode: '352',
    isoCode: 'LUX',
  ),
  //flags with M
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MK.png',
    countryFlagName: 'Macedonia',
    countryCode: '389',
    isoCode: 'MKD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MG.png',
    countryFlagName: 'Madagascar',
    countryCode: '261',
    isoCode: 'MDG',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MW.png',
    countryFlagName: 'Malawi',
    countryCode: '265',
    isoCode: 'MWI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MY.png',
    countryFlagName: 'Malaysia',
    countryCode: '60',
    isoCode: 'MYS',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MV.png',
    countryFlagName: 'Maldives',
    countryCode: '960',
    isoCode: 'MDV',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/ML.png',
    countryFlagName: 'Mali',
    countryCode: '223',
    isoCode: 'MLI',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MT.png',
    countryFlagName: 'Malta',
    countryCode: '356',
    isoCode: 'MLT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MH.png',
    countryFlagName: 'Marshall Islands',
    countryCode: '692',
    isoCode: 'MHL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MR.png',
    countryFlagName: 'Mauritania',
    countryCode: '222',
    isoCode: 'MRT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MU.png',
    countryFlagName: 'Mauritius',
    countryCode: '230',
    isoCode: 'MUS',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MX.png',
    countryFlagName: 'Mexico',
    countryCode: '52',
    isoCode: 'MEX',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/FM.png',
    countryFlagName: 'Micronesia',
    countryCode: '691',
    isoCode: 'FSM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MD.png',
    countryFlagName: 'Moldova',
    countryCode: '373',
    isoCode: 'MDA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MC.png',
    countryFlagName: 'Monaco',
    countryCode: '377',
    isoCode: 'MCO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MN.png',
    countryFlagName: 'Mongolia',
    countryCode: '976',
    isoCode: 'MNG',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/ME.png',
    countryFlagName: 'Montenegro',
    countryCode: '382',
    isoCode: 'MNE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MA.png',
    countryFlagName: 'Morocco',
    countryCode: '212',
    isoCode: 'MAR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MZ.png',
    countryFlagName: 'Mozambique',
    countryCode: '258',
    isoCode: 'MOZ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/m_flags/MM.png',
    countryFlagName: 'Myanmar',
    countryCode: '95',
    isoCode: 'MMR',
  ),
  //flags with N
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NA.png',
    countryFlagName: 'Namibia',
    countryCode: '264',
    isoCode: 'NAM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NR.png',
    countryFlagName: 'Nauru',
    countryCode: '674',
    isoCode: 'NRU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NP.png',
    countryFlagName: 'Nepal',
    countryCode: '977',
    isoCode: 'NPL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NL.png',
    countryFlagName: 'Netherlands',
    countryCode: '31',
    isoCode: 'NLD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NZ.png',
    countryFlagName: 'New Zealand',
    countryCode: '64',
    isoCode: 'NZL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NI.png',
    countryFlagName: 'Nicaragua',
    countryCode: '505',
    isoCode: 'NIC',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NE.png',
    countryFlagName: 'Niger',
    countryCode: '227',
    isoCode: 'NER',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NG.png',
    countryFlagName: 'Nigeria',
    countryCode: '234',
    isoCode: 'NGA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/KP.png',
    countryFlagName: 'North Korea',
    countryCode: '850',
    isoCode: 'PRK',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/n_flags/NO.png',
    countryFlagName: 'Norway',
    countryCode: '47',
    isoCode: 'NOR',
  ),
  //flags with O
  Countries(
    countyFlagImg: 'assets/country_flags/o_flags/OM.png',
    countryFlagName: 'Oman',
    countryCode: '968',
    isoCode: 'OMN',
  ),
  //flag with P
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PK.png',
    countryFlagName: 'Pakistan',
    countryCode: '92',
    isoCode: 'PAK',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PW.png',
    countryFlagName: 'Palau',
    countryCode: '680',
    isoCode: 'PLW',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PA.png',
    countryFlagName: 'Panama',
    countryCode: '507',
    isoCode: 'PAN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PG.png',
    countryFlagName: 'Papua New Guinea',
    countryCode: '675',
    isoCode: 'PNG',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PY.png',
    countryFlagName: 'Paraguay',
    countryCode: '595',
    isoCode: 'PRY',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PE.png',
    countryFlagName: 'Peru',
    countryCode: '51',
    isoCode: 'PER',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PH.png',
    countryFlagName: 'Philippines',
    countryCode: '63',
    isoCode: 'PHL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PL.png',
    countryFlagName: 'Poland',
    countryCode: '48',
    isoCode: 'POL',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/p_flags/PT.png',
    countryFlagName: 'Portugal',
    countryCode: '351',
    isoCode: 'PRT',
  ),
  //flag with Q
  Countries(
    countyFlagImg: 'assets/country_flags/q_flags/QA.png',
    countryFlagName: 'Qatar',
    countryCode: '974',
    isoCode: 'QAT',
  ),
  //flags with R
  Countries(
    countyFlagImg: 'assets/country_flags/r_flags/RO.png',
    countryFlagName: 'Romania',
    countryCode: '40',
    isoCode: 'ROU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/r_flags/RU.png',
    countryFlagName: 'Russia',
    countryCode: '7',
    isoCode: 'RUS',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/r_flags/RW.png',
    countryFlagName: 'Rwanda',
    countryCode: '250',
    isoCode: 'RWA',
  ),
  //flags with S
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/KN.png',
    countryFlagName: 'Saint Kitts and Nevis',
    countryCode: '1-869',
    isoCode: 'KNA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/LC.png',
    countryFlagName: 'Saint Lucia',
    countryCode: '1-758',
    isoCode: 'LCA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/VC.png',
    countryFlagName: 'Saint Vincent and the Grenadines',
    countryCode: '1-784',
    isoCode: 'VCT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/WS.png',
    countryFlagName: 'Samoa',
    countryCode: '685',
    isoCode: 'WSM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SM.png',
    countryFlagName: 'San Marino',
    countryCode: '378',
    isoCode: 'SMR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/ST.png',
    countryFlagName: 'Sao Tome and Principe',
    countryCode: '239',
    isoCode: 'STP',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SA.png',
    countryFlagName: 'Saudi Arabia',
    countryCode: '966',
    isoCode: 'SAU',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SN.png',
    countryFlagName: 'Senegal',
    countryCode: '221',
    isoCode: 'SEN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/RS.png',
    countryFlagName: 'Serbia',
    countryCode: '381',
    isoCode: 'SRB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SC.png',
    countryFlagName: 'Seychelles',
    countryCode: '248',
    isoCode: 'SYC',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SL.png',
    countryFlagName: 'Sierra Leone',
    countryCode: '232',
    isoCode: 'SLE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SG.png',
    countryFlagName: 'Singapore',
    countryCode: '65',
    isoCode: 'SGP',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SK.png',
    countryFlagName: 'Slovakia',
    countryCode: '421',
    isoCode: 'SVK',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SB.png',
    countryFlagName: 'Solomon Islands',
    countryCode: '677',
    isoCode: 'SLB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SO.png',
    countryFlagName: 'Somalia',
    countryCode: '252',
    isoCode: 'SOM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/ZA.png',
    countryFlagName: 'South Africa',
    countryCode: '27',
    isoCode: 'ZAF',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/KR.png',
    countryFlagName: 'South Korea',
    countryCode: '82',
    isoCode: 'KOR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SS.png',
    countryFlagName: 'South Sudan',
    countryCode: '211',
    isoCode: 'SSD',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/ES.png',
    countryFlagName: 'Spain',
    countryCode: '34',
    isoCode: 'ESP',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/LK.png',
    countryFlagName: 'Sri Lanka',
    countryCode: '94',
    isoCode: 'LKA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SD.png',
    countryFlagName: 'Sudan',
    countryCode: '249',
    isoCode: 'SDN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SR.png',
    countryFlagName: 'Suriname',
    countryCode: '597',
    isoCode: 'SUR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SZ.png',
    countryFlagName: 'Swaziland',
    countryCode: '268',
    isoCode: 'SWZ',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SE.png',
    countryFlagName: 'Sweden',
    countryCode: '46',
    isoCode: 'SWE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/CH.png',
    countryFlagName: 'Switzerland',
    countryCode: '41',
    isoCode: 'CHE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/s_flags/SY.png',
    countryFlagName: 'Syria',
    countryCode: '963',
    isoCode: 'SYR',
  ),
  //flags with T
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TW.png',
    countryFlagName: 'Taiwan',
    countryCode: '886',
    isoCode: 'TWN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TJ.png',
    countryFlagName: 'Tajikistan',
    countryCode: '992',
    isoCode: 'TJK',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TZ.png',
    countryFlagName: 'Tanzania',
    countryCode: '255',
    isoCode: 'TZA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TH.png',
    countryFlagName: 'Thailand',
    countryCode: '66',
    isoCode: 'THA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TG.png',
    countryFlagName: 'Togo',
    countryCode: '228',
    isoCode: 'TGO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TO.png',
    countryFlagName: 'Tonga',
    countryCode: '676',
    isoCode: 'TON',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TT.png',
    countryFlagName: 'Trinidad and Tobago',
    countryCode: '1-868',
    isoCode: 'TTO',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TN.png',
    countryFlagName: 'Tunisia',
    countryCode: '216',
    isoCode: 'TUN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TR.png',
    countryFlagName: 'Turkey',
    countryCode: '90',
    isoCode: 'TUR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TM.png',
    countryFlagName: 'Turkmenistan',
    countryCode: '993',
    isoCode: 'TKM',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/t_flags/TV.png',
    countryFlagName: 'Tuvalu',
    countryCode: '688',
    isoCode: 'TUV',
  ),
  //flag with U
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/UG.png',
    countryFlagName: 'Uganda',
    countryCode: '256',
    isoCode: 'UGA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/UA.png',
    countryFlagName: 'Ukraine',
    countryCode: '380',
    isoCode: 'UKR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/AE.png',
    countryFlagName: 'United Arab Emirates',
    countryCode: '971',
    isoCode: 'ARE',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/GB.png',
    countryFlagName: 'United Kingdom',
    countryCode: '44',
    isoCode: 'GBR',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/US.png',
    countryFlagName: 'United States',
    countryCode: '1',
    isoCode: 'USA',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/UY.png',
    countryFlagName: 'Uruguay',
    countryCode: '598',
    isoCode: 'URY',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/u_flags/UZ.png',
    countryFlagName: 'Uzbekistan',
    countryCode: '998',
    isoCode: 'UZB',
  ),
  //flag with V
  Countries(
    countyFlagImg: 'assets/country_flags/v_flags/VU.png',
    countryFlagName: 'Vanuatu',
    countryCode: '678',
    isoCode: 'VUT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/v_flags/VA.png',
    countryFlagName: 'Vatican City',
    countryCode: '379',
    isoCode: 'VAT',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/v_flags/VE.png',
    countryFlagName: 'Venezuela',
    countryCode: '58',
    isoCode: 'VEN',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/v_flags/VN.png',
    countryFlagName: 'Vietnam',
    countryCode: '84',
    isoCode: 'VNM',
  ),
  //flag with Y
  Countries(
    countyFlagImg: 'assets/country_flags/y_flags/YE.png',
    countryFlagName: 'Yemen',
    countryCode: '967',
    isoCode: 'YEM',
  ),
  //flag with Z
  Countries(
    countyFlagImg: 'assets/country_flags/z_flags/ZM.png',
    countryFlagName: 'Zambia',
    countryCode: '260',
    isoCode: 'ZMB',
  ),
  Countries(
    countyFlagImg: 'assets/country_flags/z_flags/ZW.png',
    countryFlagName: 'Zimbabwe',
    countryCode: '263',
    isoCode: 'ZWE',
  ),
];